### ISSUE TITLE
Javascript ordering and pagination isn't localized

### ISSUE THREAD

**Issue by izendegi** [marcusgreen/moodle-report_advancedgrading#6]
Hi (again),

While testing this plugin we've also detected that the ordering and pagination always is shown in English and doesn't change if the user in browsing Moodle in another language. 

The JavaScript used seems to be DataTables, and I've seen in their website that it already has a i18n mechanism, but don't know if it would be possible to add it to this plugin and make the JavaScript show in the same language of the Moodle interface:

https://datatables.net/manual/i18n

**Comment by moodleulpgc** [comment]
Hi, as for may 2023, some parts are NOT localized. 
The table header  calls {{{studentheaders}}} structure to add the student names and ID number. 

This structure is populated in locallib.php, function header_fields(), from $data['profilefields'] 
But the raw (internal) field name is used rather than get_string($field) 

So, rather than 
$data['studentheaders'] .= "<th " . $data['headerstyle'] . "><b>" . ucfirst($field) . "</b></th>";

use,
$data['studentheaders'] .= "<th " . $data['headerstyle'] . "><b>" . get_string($field) . "</b></th>";

By the way, if uppercase or not should belong to lang file.

**Comment by marcusgreen** [comment]
Thank you Enrique, thank you for the detailed information.  I will take a look at that with a view to fixing in the near future. And generally the case should be left to the lang file.

**Comment by marcusgreen** [comment]
I am closing this as the latest release has localised the PHP and removed the javascript. Please create a new ticket if I have missed localisation anywhere else. Many thanks for your feedback, you have helped improve the plugin.
